sudo: required

services:
  - docker

before_install:
  - docker build -t devam2b/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devam2b/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-us-east-2-276800044052"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY